In [12]:
import numpy as np
x = np.array(([2, 9], [1, 5], [3, 6]), dtype=float)
y = np.array(([92], [86], [89]), dtype=float)
y = y/100

def sigmoid (x):
    return 1/(1 + np.exp(-x))

def derivatives_sigmoid(x):
    return x * (1 - x)

epoch=10000 #Setting training iterations
lr=0.1 #Setting learning rate
inputlayer_neurons = 2 #number of features in data set
hiddenlayer_neurons = 3 #number of hidden layers neurons
output_neurons = 1 #number of neurons at output layer

#weight and bias initialization
wh=np.random.uniform(size=(inputlayer_neurons,hiddenlayer_neurons))
bh=np.random.uniform(size=(1,hiddenlayer_neurons))
wout=np.random.uniform(size=(hiddenlayer_neurons,output_neurons))
bout=np.random.uniform(size=(1,output_neurons))

#draws a random range of numbers uniformly of dim x*y
for i in range(epoch):
#Forward Propogation
    hinp1=np.dot(x,wh)
    neth1=hinp1 + bh
    outh1 = sigmoid(neth1)
    
    outinp1=np.dot(outh1,wout)
    neto1= outinp1+ bout
    outo1 = sigmoid(neto1)
#Backpropagation
    EO = y-outo1
    outgrad = derivatives_sigmoid(outo1)
    d_output = EO* outgrad
    
    EH = d_output.dot(wout.T)
    hiddengrad = derivatives_sigmoid(outh1)#how much hidden layer wts contributed to error
    d_hiddenlayer = EH * hiddengrad
    
    wout += outh1.T.dot(d_output) *lr# dotproduct of nextlayererror and currentlayerop
    wh += x.T.dot(d_hiddenlayer) *lr

print("Input: \n" + str(x)) 
print("Actual Output: \n" + str(y))
print("Predicted Output: \n" ,outo1)

Input: 
[[2. 9.]
 [1. 5.]
 [3. 6.]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
 [[0.89345228]
 [0.88076184]
 [0.89582481]]
